### PR TITLE
allow custom escape character

### PR DESCRIPTION
**Pull request by killroyboy**

### CODE REVIEW

**Comment by renerlemes** [comment]
@killroyboy Could you give an example of this PR?

**Comment by killroyboy** [comment]
> @killroyboy Could you give an example of this PR?

You can see an example in the test I included at: https://github.com/killroyboy/maska/blob/master/test/mask-input.test.ts#L1452-L1486

```
...
mask: '$#!99',
tokens: {
   '$': { pattern: /\$/, escape: true },
   '9': { pattern: /\d/, multiple: true }
}
...
```

**Comment by beholdr** [comment]
Thanks for PR

**Comment by beholdr** [comment]
Hmm, I was a bit hasty in accepting this pull request. Can you explain the need for such solution? The mask "$#!99" from the tests is solved by the standard escape character "!#!99". It turns out that if we add a new escape token, then the old character "!" also remains active. But why? Wouldn't it make more sense to make the escape character a general mask setting (via MaskOptions) rather than one of the tokens? @killroyboy

**Comment by killroyboy** [comment]
That's a really good point. I am migrating from `vue-input-facade` and just trying to be backward compatible with a lot of existing masks within my application. So that tainted my approach. 

Feel free to revert and implement a better solution. I actually created a workaround within my app while waiting for this PR and the subsequent new version.

**Pull request merged**
